# Site settings
title: A blog about coding and deep learning
description: A blog about deep learning in python
baseurl: "" # the subpath of your site, e.g. /blog
url: "ranarag.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ranarag
user_description: Deep Learning Enthusiast
user_title: Anurag Roy
email: anu15roy@gmail.com
twitter_username: lorem_ipsum
github_username:  ranarag
gplus_username:  lorem_ipsum
disqus_username: disqus_X04Ct4XEKT

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
